# This is a basic workflow to help you get started with Actions

name: build_620q_uclibc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: prepare opencv-library
        run: |
          mkdir -p ./3rdparty
          wget https://github.com/AXERA-TECH/ax-samples/releases/download/v0.6/opencv-arm-uclibc-linux.zip
          unzip opencv-arm-uclibc-linux.zip -d ./3rdparty

      - name: build
        run: |
          mkdir build
          cd build
          git clone https://github.com/AXERA-TECH/ax620q_bsp_sdk.git
          export ax_bsp=$PWD/ax620q_bsp_sdk/msp/out/arm_uclibc/
          echo $ax_bsp          
          wget https://github.com/AXERA-TECH/ax620q_bsp_sdk/releases/download/v2.0.0/arm-AX620E-linux-uclibcgnueabihf_V3_20240320.tgz
          tar -zxf arm-AX620E-linux-uclibcgnueabihf_V3_20240320.tgz
          export PATH=$PATH:arm-AX620E-linux-uclibcgnueabihf/bin/
          arm-AX620E-linux-uclibcgnueabihf-gcc -v
          cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm-AX620E-linux-uclibcgnueabihf.toolchain.cmake -DBSP_MSP_DIR=${ax_bsp}/ -DAXERA_TARGET_CHIP=ax620q ..
          make -j8
          make install
